language: java

jdk:
  - openjdk11

branches:
  only:
    - master
    - development

script:
  - mvn clean package

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: coverage/target/site/jacoco-aggregate
  on:
    branch:
      - master
      - development
